# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
# source: _11_create_hyrex_cron_job_run_details_table.sql
import dataclasses

import sqlalchemy
import sqlalchemy.ext.asyncio

from . import models


CREATE_CRON_JOB_RUN_DETAILS_TABLE = """-- name: create_cron_job_run_details_table \\:exec
CREATE TABLE IF NOT EXISTS hyrex_cron_job_run_details (
  jobid        bigint      NOT NULL,
  runid        bigserial   PRIMARY KEY,
  command      text        NOT NULL,
  status       cron_job_status_enum,
  schedule_time timestamptz not null,
  start_time   timestamptz,
  end_time     timestamptz,
  UNIQUE (jobid, schedule_time)
)
"""


@dataclasses.dataclass()
class CreateCronJobRunDetailsTableParams:

    pass

class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_cron_job_run_details_table(self, arg: CreateCronJobRunDetailsTableParams) -> None:
        self._conn.execute(sqlalchemy.text(CREATE_CRON_JOB_RUN_DETAILS_TABLE))


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_cron_job_run_details_table(self, arg: CreateCronJobRunDetailsTableParams) -> None:
        await self._conn.execute(sqlalchemy.text(CREATE_CRON_JOB_RUN_DETAILS_TABLE))
