# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
# source: advance_workflow_run.sql
import dataclasses
from typing import Any, AsyncIterator, Iterator, Optional
import uuid

import sqlalchemy
import sqlalchemy.ext.asyncio

from . import models


ADVANCE_WORKFLOW_RUN = """-- name: advance_workflow_run \\:many
WITH latest_attempts AS (
    -- Get the latest attempt for each durable_id
    SELECT DISTINCT ON (durable_id) durable_id,
                                    status
    FROM hyrex_task_run
    WHERE hyrex_task_run.workflow_run_id = :p1
    ORDER BY durable_id, attempt_number DESC),
     tasks_ready_to_queue AS (
         -- Find waiting tasks where all dependencies are successful
         SELECT t.id
         FROM hyrex_task_run t
         WHERE t.workflow_run_id = :p1
           AND t.status = 'waiting'
           AND (
             -- Handle both cases\\: no dependencies, or all dependencies are successful
             t.workflow_dependencies IS NULL
                 OR NOT EXISTS (
                 -- Check if there are any dependencies that aren't successful
                 SELECT 1
                 FROM unnest(t.workflow_dependencies) AS dep_durable_id
                          LEFT JOIN latest_attempts la ON la.durable_id = dep_durable_id
                 WHERE la.status IS NULL
                    OR la.status != 'success')
             ))
UPDATE hyrex_task_run
SET status = 'QUEUED'\\:\\:task_run_status
WHERE id IN (SELECT id FROM tasks_ready_to_queue)
RETURNING status, workflow_run_id
"""


@dataclasses.dataclass()
class AdvanceWorkflowRunParams:
    workflow_run_id: Optional[uuid.UUID]


@dataclasses.dataclass()
class AdvanceWorkflowRunRow:
    status: Any
    workflow_run_id: Optional[uuid.UUID]


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def advance_workflow_run(self, arg: AdvanceWorkflowRunParams) -> Iterator[AdvanceWorkflowRunRow]:
        result = self._conn.execute(sqlalchemy.text(ADVANCE_WORKFLOW_RUN), {"p1": arg.workflow_run_id})
        for row in result:
            yield AdvanceWorkflowRunRow(
                status=row[0],
                workflow_run_id=row[1],
            )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def advance_workflow_run(self, arg: AdvanceWorkflowRunParams) -> AsyncIterator[AdvanceWorkflowRunRow]:
        result = await self._conn.stream(sqlalchemy.text(ADVANCE_WORKFLOW_RUN), {"p1": arg.workflow_run_id})
        async for row in result:
            yield AdvanceWorkflowRunRow(
                status=row[0],
                workflow_run_id=row[1],
            )
