# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
# source: create_job_source_type_enum.sql
import dataclasses

import sqlalchemy
import sqlalchemy.ext.asyncio

from . import models


CREATE_JOB_SOURCE_TYPE_ENUM = """-- name: create_job_source_type_enum \\:exec
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'job_source_type') THEN
        CREATE TYPE job_source_type AS ENUM ('SYSTEM', 'TASK', 'APPLICATION');
    END IF;
END
$$
"""


@dataclasses.dataclass()
class CreateJobSourceTypeEnumParams:

    pass

class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_job_source_type_enum(self, arg: CreateJobSourceTypeEnumParams) -> None:
        self._conn.execute(sqlalchemy.text(CREATE_JOB_SOURCE_TYPE_ENUM))


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_job_source_type_enum(self, arg: CreateJobSourceTypeEnumParams) -> None:
        await self._conn.execute(sqlalchemy.text(CREATE_JOB_SOURCE_TYPE_ENUM))
