# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
# source: create_hype_cron_job_status_enum.sql
import dataclasses

import sqlalchemy
import sqlalchemy.ext.asyncio

from . import models


CREATE_HYPE_CRON_JOB_STATUS_ENUM = """-- name: create_hype_cron_job_status_enum \\:exec
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'hype_cron_job_status_enum' AND typnamespace = 'public'\\:\\:regnamespace) THEN
        CREATE TYPE public.hype_cron_job_status_enum AS ENUM (
            'SUCCESS',
            'QUEUED',
            'PROCESSING',
            'FAILED'
        );
    END IF;
END $$
"""


@dataclasses.dataclass()
class CreateHypeCronJobStatusEnumParams:

    pass

class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_hype_cron_job_status_enum(self, arg: CreateHypeCronJobStatusEnumParams) -> None:
        self._conn.execute(sqlalchemy.text(CREATE_HYPE_CRON_JOB_STATUS_ENUM))


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_hype_cron_job_status_enum(self, arg: CreateHypeCronJobStatusEnumParams) -> None:
        await self._conn.execute(sqlalchemy.text(CREATE_HYPE_CRON_JOB_STATUS_ENUM))
