# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import requests_pb2 as requests__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x17hyrex.performanceserver\x1a\x0erequests.proto2\xd4\x07\n\x0eGatewayService\x12\x64\n\x07\x45nqueue\x12+.hyrex.performanceserver.EnqueueTaskRequest\x1a,.hyrex.performanceserver.EnqueueTaskResponse\x12\x64\n\x07\x44\x65queue\x12+.hyrex.performanceserver.DequeueTaskRequest\x1a,.hyrex.performanceserver.DequeueTaskResponse\x12\x62\n\tGetQueues\x12).hyrex.performanceserver.GetQueuesRequest\x1a*.hyrex.performanceserver.GetQueuesResponse\x12n\n\rGetTaskStatus\x12-.hyrex.performanceserver.GetTaskStatusRequest\x1a..hyrex.performanceserver.GetTaskStatusResponse\x12h\n\x0bMarkSuccess\x12+.hyrex.performanceserver.MarkSuccessRequest\x1a,.hyrex.performanceserver.MarkSuccessResponse\x12\x65\n\nMarkFailed\x12*.hyrex.performanceserver.MarkFailedRequest\x1a+.hyrex.performanceserver.MarkFailedResponse\x12\\\n\x07GetTask\x12\'.hyrex.performanceserver.GetTaskRequest\x1a(.hyrex.performanceserver.GetTaskResponse\x12z\n\x0fGetDurableTasks\x12\x32.hyrex.performanceserver.GetDurableRunTasksRequest\x1a\x33.hyrex.performanceserver.GetDurableRunTasksResponse\x12w\n\x10RegisterExecutor\x12\x30.hyrex.performanceserver.RegisterExecutorRequest\x1a\x31.hyrex.performanceserver.RegisterExecutorResponseB\x08Z\x06proto/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006proto/'
  _globals['_GATEWAYSERVICE']._serialized_start=59
  _globals['_GATEWAYSERVICE']._serialized_end=1039
# @@protoc_insertion_point(module_scope)
