syntax = "proto3";

package hyrex.performanceserver;

option go_package = "proto/";

import "postgres.proto";
import "valkey.proto";

service GatewayService {
  rpc Enqueue(EnqueueTaskRequest) returns (EnqueueTaskResponse);
  rpc Dequeue(DequeueTaskRequest) returns (DequeueTaskResponse);
  rpc GetQueues(GetQueuesRequest) returns (GetQueuesResponse);
  rpc GetTaskStatus(GetTaskStatusRequest) returns (GetTaskStatusResponse);
  rpc MarkSuccess(MarkSuccessRequest) returns (MarkSuccessResponse);
  rpc MarkFailed(MarkFailedRequest) returns (MarkFailedResponse);
  rpc GetTask(GetTaskRequest) returns (GetTaskResponse);
  rpc GetDurableTasks(GetDurableRunTasksRequest) returns (GetDurableRunTasksResponse);
  }
