syntax = "proto3";

package hyrex.performanceserver;

option go_package = "proto/";

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";
import "task.proto";


// VALKEY REQUESTS
message EnqueueRequest {
  string id = 1;
  string durable_id = 2;
  string root_id = 3;
  optional string workflow_run_id = 4;
  repeated string workflow_dependencies = 5;
  optional string parent_id = 6;
  TaskStatus status = 7;
  string task_name = 8;
  bytes args = 9; // JSON serialized as bytes
  string queue = 10;
  int32 max_retries = 11;
  Priority priority = 12;
  optional int32 timeout_seconds = 13;
  optional string idempotency_key = 14;
  optional google.protobuf.Timestamp scheduled_start = 15;
}

message EnqueueResponse {}

message DequeueRequest {
  string executor_id = 1;
  string queue = 2;
}

message DequeueResponse {
    TaskRun task_run = 1;
  }
  
message GetQueuesRequest {
  int32 max_num_queues = 1;
  string pattern = 2;
}

message GetQueuesResponse {
  string message = 1;
  repeated string queues = 2;
}

message GetTaskRunRequest {
  string task_id = 1;
}

message GetTaskRunResponse {
  TaskRun task_run = 1;
}

message GetTaskRunStatusRequest {
  string task_id = 1;
}

message GetTaskRunStatusResponse {
  TaskStatus status = 1;
}

message MarkSuccessRequest {
  string task_id = 1;
  optional string result = 2;
}

message MarkSuccessResponse {}

message MarkFailedRequest {
  string task_id = 1;
}

message MarkFailedResponse {}

message GetDurableTaskRunsRequest {
  string durable_id = 1;
}

message GetDurableTaskRunsResponse {
  repeated TaskRun task_runs = 2;
}

message SetLogLinkRequest {
  string task_id = 1;
  string log_link = 2;
}

message SetLogLinkResponse {}

// POSTGRES REQUESTS
message RegisterTaskDefRequest {
  TaskDef task_def = 1;
}

message RegisterTaskDefResponse {}

message GetTaskDefRequest {
  string task_name = 1;
}

message GetTaskDefResponse {
  TaskDef task_def = 1;
}

message GetAllTaskDefsRequest {}

message GetAllTaskDefsResponse {
  repeated TaskDef task_defs = 1;
}

message RegisterCronRequest {
  // TODO
}

message RegisterCronResponse {}

message RegisterExecutorRequest {
  string executor_id = 1;
  string executor_name = 2;
  string queue_pattern = 3;
  repeated string queues = 4;
  string worker_name = 5;
}

message RegisterExecutorResponse {}

message UpdateExecutorQueuesRequest {
  string executor_id = 1;
  repeated string queues = 2;
}

message UpdateExecutorQueuesResponse {}

message RegisterAppRequest {
  google.protobuf.Struct app_info = 1;
}

message RegisterAppResponse {}

message AcquireSchedulerLockRequest {
  string worker_name = 1;
  string duration = 2;
}

message AcquireSchedulerLockResponse {
  optional int32 lock_id = 1;
}

// Internal connection test
message TestConnectionRequest {}

message TestConnectionResponse {}
