syntax = "proto3";

package hyrex.performanceserver;

option go_package = "proto/";

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";
import "task.proto";


// VALKEY REQUESTS
message EnqueueRequest {
  string id = 1;
  string durable_id = 2;
  string root_id = 3;
  optional string workflow_run_id = 4;
  repeated string workflow_dependencies = 5;
  optional string parent_id = 6;
  string task_name = 7;
  bytes args = 8; // JSON serialized as bytes
  string queue = 9;
  int32 max_retries = 10;
  optional int32 attempt_number = 11;
  Priority priority = 12;
  optional int32 timeout_seconds = 13;
  optional string idempotency_key = 14;
  optional google.protobuf.Timestamp scheduled_start = 15;
}

message DequeueRequest {
  string executor_id = 1;
  string queue = 2;
}

message DequeueResponse {
    TaskRun task_run = 1;
  }
  
message GetQueuesRequest {
  int32 max_num_queues = 1;
  string pattern = 2;
}

message GetQueuesResponse {
  string message = 1;
  repeated string queues = 2;
}

message RetryTaskRunRequest {
  string task_run_id = 1;
  int32 backoff_seconds = 2;
}

message GetTaskRunRequest {
  string task_run_id = 1;
}

message GetTaskRunResponse {
  TaskRun task_run = 1;
}

message GetTaskRunStatusRequest {
  string task_run_id = 1;
}

message GetTaskRunStatusResponse {
  TaskStatus status = 1;
}

message TaskRunHeartbeatRequest {
  repeated string task_run_ids = 1;
  google.protobuf.Timestamp timestamp = 2;
}

message MarkSuccessRequest {
  string task_run_id = 1;
  optional string result = 2;
}

message MarkFailedRequest {
  string task_run_id = 1;
}

message GetDurableTaskRunsRequest {
  string durable_id = 1;
}

message GetDurableTaskRunsResponse {
  repeated TaskRun task_runs = 2;
}

message SetLogLinkRequest {
  string task_run_id = 1;
  string log_link = 2;
}

// POSTGRES REQUESTS
message RegisterTaskDefRequest {
  TaskDef task_def = 1;
}

message GetTaskDefRequest {
  string task_name = 1;
}

message GetTaskDefResponse {
  TaskDef task_def = 1;
}

message GetAllTaskDefsRequest {}

message GetAllTaskDefsResponse {
  repeated TaskDef task_defs = 1;
}

message RegisterCronRequest {
  // TODO
}

message RegisterExecutorRequest {
  string executor_id = 1;
  string executor_name = 2;
  string queue_pattern = 3;
  repeated string queues = 4;
  string worker_name = 5;
}

message UpdateExecutorQueuesRequest {
  string executor_id = 1;
  repeated string queues = 2;
}

message UpdateExecutorStatsRequest {
  string executor_id = 1;
  google.protobuf.Struct executor_stats = 2;
}

message ExecutorHeartbeatRequest {
  repeated string executor_ids = 1;
  google.protobuf.Timestamp timestamp = 2;
}

message DisconnectExecutorRequest {
  string executor_id = 1;
}

message MarkRunningTasksLostRequest {
  string executor_id = 1;
}

message RegisterAppRequest {
  google.protobuf.Struct app_info = 1;
}

message WriteLogsRequest {
  string task_run_id = 1;
  string logs = 2;
}

message RegisterWorkflowRequest {
  string workflow_name = 1;
  string source_code = 2;
  string workflow_dag_json = 3;
  optional google.protobuf.Struct workflow_arg_schema = 4;
  google.protobuf.Struct default_config = 5;
  optional string cron = 6;
}

message SendWorkflowRunRequest {
  string workflow_run_id = 1;
  string workflow_name = 2;
  google.protobuf.Struct args = 3;
  string queue = 4;
  optional int32 timeout_seconds = 5;
  optional string idempotency_key = 6;
}

message GetWorkflowRunArgsRequest {
  string workflow_run_id = 1;
}

message GetWorkflowRunArgsResponse {
  google.protobuf.Struct args = 1;
}

message AdvanceWorkflowRunRequest {
  string workflow_run_id = 1;
}

message GetWorkflowDurableRunsRequest {
  string workflow_run_id = 1;
}

message GetWorkflowDurableRunsResponse {
  repeated string durable_ids = 1;
}

message TryToCancelDurableRunRequest {
  string durable_id = 1;
}

message GetTaskRunsUpForCancelResponse {
  repeated string task_run_ids = 1;
}

message MarkCanceledRequest {
  string task_run_id = 1;
}

message KVStoreSetRequest {
  string key = 1;
  string value = 2;
  optional bool overwrite = 3;
}

message KVStoreGetRequest {
  string key = 1;
}

message KVStoreGetResponse {
  string value = 1;
}
