syntax = "proto3";

package hyrex.performanceserver;

option go_package = "proto/";

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";
import "task.proto";


// VALKEY REQUESTS
message EnqueueTaskRequest {
  string id = 1;
  string durable_id = 2;
  string root_id = 3;
  optional string workflow_run_id = 4;
  repeated string workflow_dependencies = 5;
  optional string parent_id = 6;
  TaskStatus status = 7;
  string task_name = 8;
  bytes args = 9; // JSON serialized as bytes
  string queue = 10;
  int32 max_retries = 11;
  Priority priority = 12;
  optional int32 timeout_seconds = 13;
  optional string idempotency_key = 14;
  optional google.protobuf.Timestamp scheduled_start = 15;
}

message EnqueueTaskResponse {
  string message = 1;
}

message DequeueTaskRequest {
  string executor_id = 1;
  string queue = 2;
}

message DequeueTaskResponse {
    string message = 1;
    TaskRun task = 2;
  }
  
message GetQueuesRequest {
  int32 max_num_queues = 1;
  string pattern = 2;
}

message GetQueuesResponse {
  string message = 1;
  repeated string queues = 2;
}

message GetTaskRunRequest {
  string task_id = 1;
}

message GetTaskRunResponse {
  string message = 1;
  TaskRun task = 2;
}

message GetTaskStatusRequest {
  string task_id = 1;
}

message GetTaskStatusResponse {
  string message = 1;
  TaskStatus status = 2;
}

message MarkSuccessRequest {
  string task_id = 1;
  optional string result = 2;
}

message MarkSuccessResponse {
  string message = 1;
}

message MarkFailedRequest {
  string task_id = 1;
}

message MarkFailedResponse {
  string message = 1;
}

message GetDurableRunTasksRequest {
  string durable_id = 1;
}

message GetDurableRunTasksResponse {
  string message = 1;
  repeated TaskRun tasks = 2;
}

message SetLogLinkRequest {
  string task_id = 1;
  string log_link = 2;
}

message SetLogLinkResponse {
  string message = 1;
}

// POSTGRES REQUESTS
message RegisterTaskDefRequest {
  Task task = 1;
}

message RegisterTaskDefResponse {}

message GetTaskDefRequest {
  string task_name = 1;
}

message GetTaskDefResponse {
  Task task = 1;
}

message GetAllTaskDefsRequest {}

message GetAllTaskDefsResponse {
  repeated Task tasks = 1;
}

message RegisterCronRequest {
  // TODO
}

message RegisterCronResponse {}

message RegisterExecutorRequest {
  string executor_id = 1;
  string executor_name = 2;
  string queue_pattern = 3;
  repeated string queues = 4;
  string worker_name = 5;
}

message RegisterExecutorResponse {
  string message = 1;
}

message UpdateExecutorQueuesRequest {
  string executor_id = 1;
  repeated string queues = 2;
}

message UpdateExecutorQueuesResponse {
  string message = 1;
}

message RegisterAppRequest {
  google.protobuf.Struct app_info = 1;
}

message RegisterAppResponse {
  string message = 1;
}

message AcquireSchedulerLockRequest {
  string worker_name = 1;
  string duration = 2;
}

message AcquireSchedulerLockResponse {
  string message = 1;
  optional int32 lock_id = 2;
}

// Internal connection test
message TestConnectionRequest {
  string message = 1;
}

message TestConnectionResponse {
  string message = 1;
}
